project:
  type: website
  output-dir: docs

website:
  title: "Test_dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - dashboard.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
